### ISSUE TITLE
Unable to print PDF in windows 7 x32

### ISSUE THREAD

**Issue by kamaldeepoodles** [tojocky/node-printer#103]
Hi, as per the doc, I installed "imagemagick" using command "npm install imagemagick-native" in the examples directory of node-printer. The installation was successful with following logs:-

``` console
C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native>if not defined npm_config_node_gyp (
node "C:\Users\xz\AppData\Roaming\nvm\v0.12.7\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  imagemagick.cc
c:\program files\imagemagick-6.8.5-q16\include\magick/pixel-accessor.h(163): warning C4244: 'argument' : conversion from 'double' to 'const MagickCore::MagickRealType',
possible loss of data [C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagem
agick.vcxproj]
C:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:
\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(131): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(304): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(344): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(364): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(405): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(572): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(742): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(817): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(890): warning C4344: behavior change: use of explicit template arguments results in call to 'v8::Local<T> NanNew<v8::String,char*>(A0)' [C:\Users\x
z\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          with
          [
              T=v8::String,
              A0=char *
          ]
          but the regular function 'v8::Local<T> NanNew(const char *)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *)' to be called then you need to make it an explicit specialization
          with
          [
              T=v8::String
          ]
  win_delay_load_hook.c
     Creating library C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\Release
  \imagemagick.lib and object C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build
  \Release\imagemagick.exp
  Generating code
  Finished generating code
  imagemagick.vcxproj -> C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\Rele
  ase\\imagemagick.node
PacificCX@0.0.1 C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples
└── imagemagick-native@1.8.0  extraneous

C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples>
```

But when I tried to run the printPDFInWindows.js, it showed me the following error in browser console:-

![webkit](https://cloud.githubusercontent.com/assets/10527158/11953211/70903ef8-a8c4-11e5-8a0d-11bb1fac7427.jpg)

So after this I tried to rebuild the imagemagick-native project first using "node-gyp rebuild" command in this directory i.e. ".\node_modules\imagemagick-native" but got the following **error**

``` console
C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@0.12.7 | win32 | ia32
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\xz\\AppData\\Roaming\\nvm\\v0.12.7\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xz\\Documents\\pacificCx\\nodeApplication\\testndelete\\printerTest\\node_modules\\printer\\examples\\node_modules\\imagemagick-native\\
build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xz\\AppData\\Roaming\\nvm\\v0.12.7\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xz\\.node-gyp\\0.12.7\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xz\\.node-gyp\\0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\xz\\AppData\\Roaming\\nvm\\v0.12.7\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\xz\\Documents\\pacificCx\\nodeApplication\\testndelete\\printerTest\\node_modules\\printer\\examples\\node_modules\\im
agemagick-native',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\xz\\Documents\\pacificCx\\nodeApplication\\testndelete\\printerTest\\node_modules\\printer\\examples\\node_modules\\imagemagick-native\\
build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\ex
amples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Documents\pacific
Cx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xz\AppData\Roaming\nvm\v0.12.7\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native>
                                  
```

So next I tried to rebuild the imagemagick-native project first using "nw-gyp rebuild --target=0.12.3" command in this directory i.e. ".\node_modules\imagemagick-native". This time it was **success** with some warnings:-

``` console
C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native>nw-gyp rebuild --target=0.12.3
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.12.7 | win32 | ia32
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\xz\\AppData\\Roaming\\nvm\\v0.12.7\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xz\\Documents\\pacificCx\\nodeApplication\\testndelete\\printerTest\\node_modules\\printer\\examples\\node_modules\\imagemagick-native\\
build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xz\\AppData\\Roaming\\nvm\\v0.12.7\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xz\\.nw-gyp\\0.12.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xz\\.nw-gyp\\0.12.3',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\xz\\Documents\\pacificCx\\nodeApplication\\testndelete\\printerTest\\node_modules\\printer\\examples\\node_modules\\im
agemagick-native',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\xz\\Documents\\pacificCx\\nodeApplication\\testndelete\\printerTest\\node_modules\\printer\\examples\\node_modules\\imagemagick-native\\
build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  imagemagick.cc
c:\program files\imagemagick-6.8.5-q16\include\magick/pixel-accessor.h(163): warning C4244: 'argument' : conversion from 'double' to 'const MagickCore::MagickRealType',
possible loss of data [C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagem
agick.vcxproj]
C:\Users\xz\.nw-gyp\0.12.3\deps\v8\include\vcruntime.h(92): warning C4005: '_CRT_STRINGIZE' : macro redefinition [C:\Users\xz\Documents\pacificCx\nodeApplication\testnde
lete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          C:\Program Files\Microsoft Visual Studio 10.0\VC\include\crtdefs.h(72) : see previous definition of '_CRT_STRINGIZE'
C:\Users\xz\.nw-gyp\0.12.3\deps\v8\include\vcruntime.h(95): warning C4005: '_CRT_WIDE' : macro redefinition [C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\
printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          C:\Program Files\Microsoft Visual Studio 10.0\VC\include\crtdefs.h(77) : see previous definition of '_CRT_WIDE'
C:\Users\xz\.nw-gyp\0.12.3\deps\v8\include\vcruntime.h(156): warning C4005: '__CRTDECL' : macro redefinition [C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete
\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          C:\Program Files\Microsoft Visual Studio 10.0\VC\include\crtdefs.h(530) : see previous definition of '__CRTDECL'
C:\Users\xz\.nw-gyp\0.12.3\deps\v8\include\vcruntime.h(283): warning C4005: '_CRT_WARNING' : macro redefinition [C:\Users\xz\Documents\pacificCx\nodeApplication\testndel
ete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          C:\Program Files\Microsoft Visual Studio 10.0\VC\include\crtwrn.h(24) : see previous definition of '_CRT_WARNING'
..\src\imagemagick.cc(131): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(304): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(344): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(364): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(405): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(572): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(742): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(817): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Documents\pacificCx\nodeApplicati
on\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(890): warning C4344: behavior change: use of explicit template arguments results in call to 'v8::Local<T> NanNew<v8::String,char*>(A0)' [C:\Users\x
z\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          with
          [
              T=v8::String,
              A0=char *
          ]
          but the regular function 'v8::Local<T> NanNew(const char *)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *)' to be called then you need to make it an explicit specialization
          with
          [
              T=v8::String
          ]
     Creating library C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\Release
  \imagemagick.lib and object C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build
  \Release\imagemagick.exp
  Generating code
  Finished generating code
  imagemagick.vcxproj -> C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native\build\Rele
  ase\\imagemagick.node
gyp info ok

C:\Users\xz\Documents\pacificCx\nodeApplication\testndelete\printerTest\node_modules\printer\examples\node_modules\imagemagick-native>
                                  
```

But now while running the project to print PDF, I got following error in browser console.

![webkit2](https://cloud.githubusercontent.com/assets/10527158/11953705/3cfe5f1c-a8c8-11e5-8e0c-437e2a4e711b.jpg)

Here is my code which I tried to run:-

``` javascript
// Windows does not support PDF formats, but you can use imagemagick-native to achieve conversion from PDF to EMF.

var printer = require("../lib"),
    imagemagick, // will be loaded later with proper error.
    fs = require('fs'),
    filename = 'Test2.pdf',
    printername = 'POS58';

if(process.platform !== 'win32') {
    throw 'This application can be run only on win32 as a demo of print PDF image'
}

if(!filename) {
    throw 'PDF file name is missing. Please use the following params: <filename> [printername]'
}

try {
    imagemagick = require('imagemagick-native');
} catch(e) {
    throw 'please install imagemagick-native: `npm install imagemagick-native`'
}

var data = fs.readFileSync(filename);

console.log('data: ' + data.toString().substr(0, 20));

//console.log(imagemagick.identify({srcData: data}));

// First convert PDF into
imagemagick.convert({
    srcData: data,
    srcFormat: 'PDF',
    format: 'EMF',
}, function(err, buffer) {
    if (err) {
        throw 'something went wrong on converting to EMF: ' + err;
    }

    // Now we have EMF file, send it to printer as EMF format
    printer.printDirect({
        data: buffer,
        type: 'EMF',
        success: function(id) {
            console.log('printed with id ' + id);
        },
        error: function(err) {
            console.error('error on printing: ' + err);
        }
    })
})
```

**Please look into the issue and oblige.**

**Comment by kamaldeepoodles** [comment]
Jocky please look into the issue...

**Comment by Klemen1337** [comment]
+1 I have the same problem.

**Comment by randianb** [comment]
+1

**Comment by tojocky** [comment]
Hi, I think you need to open a issue on imagemagick project.
PDF print on windows is not a finished project because it requires more time to investigate on the proper solution:
 - imagemagick if it convert correctly all PDs format
 - to finish https://github.com/tojocky/node-pdfium (pdfium plugin from chromium project)

Unfortunately I don't have this time available. Feel free to propose your ideas and PR.

**Comment by josecols** [comment]
If you check the docs on http://www.imagemagick.org/script/formats.php, there is no support for writing EMF files, just Read. See the Mode column.

**Comment by keyiis** [comment]
I have same problem,i tried convert png to buffer,but not work.

**Comment by tojocky** [comment]
https://github.com/tojocky/node-printer/issues/29
