### ISSUE TITLE
Cannot find module './node_printer_linux_ia32.node'

### ISSUE THREAD

**Issue by bgobi1991** [tojocky/node-printer#111]
Hi Team,

I have given below error when execute get "node print_raw.js"

module.js:338
    throw err;
    ^

Error: Cannot find module './node_printer_linux_ia32.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sathish/nodejs/node-printer-master/lib/printer.js:12:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by tojocky** [comment]
Could you please check if you have this file or any file with *.node in the build folder?
From the folder it looks you just downloaded the module from git and tried to run.
before please recompile with C++ "node-gyp rebuild"
A recommended steps is to install it instead of just clone from git.

**Comment by migasn** [comment]
I have a problem on printing international characters on zebra example. For instance if I try to print the Ç character is printed a character before Ç. Anyone else had the same problem.

Best Regards, Miguel

**Comment by tojocky** [comment]
Check you printer and how you encode from node.js. by default is UTF8.

**Comment by tojocky** [comment]
Closing this issue because it has lack of interest.

**Comment by migasn** [comment]
Well, I think it's not a best way to answer my question. However, I challange you to print just one international character like (Ç) on a RAW printer only with this changes.
