### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by dbashyal** [tojocky/node-printer#121]
```

C:\_projects\node projects\printer>npm install printer

> printer@0.2.1 install C:\_projects\node projects\printer\node_modules\printer
> node-gyp rebuild


C:\_projects\node projects\printer\node_modules\printer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) a
dd the location of the component to the system path if it is installed elsewhere.  [C:\_projects\node projects\printer\node_modules\printer\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\_projects\node projects\printer\node_modules\printer
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
C:\_projects\node projects\printer
+-- gyp@0.5.0
`-- node-gyp@3.3.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\_projects\node projects\printer\package.json'
npm WARN printer No description
npm WARN printer No repository field.
npm WARN printer No README data
npm WARN printer No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer" "--python=C:\\Python27\\python.exe"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! printer@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the printer@0.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs printer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\_projects\node projects\printer\npm-debug.log
```

**Comment by tojocky** [comment]
Please read the error: "Could not load the Visual C++ component "VCBuild.exe""
The issue is your Visual Studio. I suspect it was not installed properly or node-gyp loaded the default Visual Studio, which is not supported. You can specify what Visual Studio version you want to use if you have multiple installations.

**Comment by dbashyal** [comment]
how do I specify which version to use?

**Comment by tojocky** [comment]
Add to node-gyp the parameter --msvs-version=2013 for VS 2013

**Comment by dbashyal** [comment]
Thx - fixed. 

Steps I followed - http://dltr.org/blog/error/585/How-to-fix-node-gyp-rebuild-errors-on-windows
