### ISSUE TITLE
Check if cups-config is available

### ISSUE THREAD

**Issue by IonicaBizau** [tojocky/node-printer#126]
Hey @tojocky! Nice module! :sparkle: 

I got the following error:

```sh
> printer@0.2.1 install /home/ionicabizau/node-printer
> node-gyp rebuild

/bin/sh: 1: cups-config: not found
```

I solved it by running `sudo apt install libcups2-dev`, but instead of crashing like this, it should show a nice error.

**Comment by tojocky** [comment]
Thanks for using this module. feel free to contribute with a PR.

**Comment by seiyria** [comment]
why was this closed if it wasn't fixed? this is still a problem.

**Comment by taylorqj** [comment]
Also experiencing this issue building on GitLab using image `node:boron`.

Calling `yarn` and immediately fails with:

```
[4/4] Building fresh packages...
error /builds/yobi/yobi-client/node_modules/printer: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /builds/yobi/yobi-client/node_modules/printer
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v7.10.0/node-v7.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.10.0/node-v7.10.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.10.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/builds/yobi/yobi-client/node_modules/printer/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/7.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/7.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/builds/yobi/yobi-client/node_modules/printer',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: 1: cups-config: not found
gyp: Call to 'cups-config --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.24-coreos
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /builds/yobi/yobi-client/node_modules/printer
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I've added `apt-get install libcups2-dev` to the build script and it can't seem to find that package.

**Comment by ZiniaSult** [comment]
Nice module but I got the following error whenever trying to run the following command:

`sudo npm run-script addAdmin`

Error is as following: 
![Screenshot from 2020-02-18 14-27-48](https://user-images.githubusercontent.com/10472577/74717643-f2aa4200-525a-11ea-926e-055cd576d4f7.png)
