### ISSUE TITLE
publish v0.3.0 to npm?

### ISSUE THREAD

**Issue by feit** [tojocky/node-printer#151]
can not install from git ` npm install git+https://github.com/tojocky/node-printer.git`
```
node-pre-gyp ERR! Tried to download(404): https://github.com/tojocky/node-printer/releases/download/0.3.0/node_printer-v0.3.0-node-v48-win32-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for printer@0.3.0 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp)

LINK : fatal error LNK1181: can not open input file “gdi32.lib” [C:\Users\feit\codes\test\node_modules\printer\build\node_prin
ter.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\feit\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\feit\\AppData\\Roaming\\nvm\\v6.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\feit\\codes\\test\\node_modules\\printer\\lib\\node_printer.node" "--module_name=node_printer" "--module_path=C:\\Users\\feit\\codes\\test\\node_modules\\printer\\lib"
```

**Comment by R1Daneel** [comment]
Is there an estimate for the release of the 0.3.0 version?

**Comment by tojocky** [comment]
it should be soon. the version 0.3.0 is not ready yet.

**Comment by R1Daneel** [comment]
Do you need some help in some task?
