### ISSUE TITLE
ES2015 throws an error ReferenceError: i is not defined

### ISSUE THREAD

**Issue by c316** [tojocky/node-printer#155]
I can run the example printFile.js with the ```node printFile.js``` command, but if I try to run this with ES2015 using babel I get an error. 

What do I need to do to get this to run with es2015? 

```
MacBook-Pro:print username$ npm run print

> print@1.0.0 print /Users/username/Documents/Dev/print
> babel-node --presets es2015 printFile.js

platform: darwin
try to print file:  1output.pdf
/Users/username/Documents/Dev/print/lib/printer.js:128
    for (i in printers) {
         ^

ReferenceError: i is not defined
    at getPrinters (/Users/username/Documents/Dev/print/lib/printer.js:129:9)
    at getDefaultPrinterName (/Users/username/Documents/Dev/print/lib/printer.js:62:17)
    at Object.printFile (/Users/username/Documents/Dev/print/lib/printer.js:295:19)
    at Object.<anonymous> (/Users/username/Documents/Dev/print/printFile.js:9:11)
    at Module._compile (module.js:413:34)
    at loader (/Users/username/Documents/Dev/print/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/username/Documents/Dev/print/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/username/.nvm/versions/node/v5.10.1/bin/node" "/Users/username/.nvm/versions/node/v5.10.1/bin/npm" "run" "print"
npm ERR! node v5.10.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! print@1.0.0 print: `babel-node --presets es2015 printFile.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the print@1.0.0 print script 'babel-node --presets es2015 printFile.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the print package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets es2015 printFile.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs print
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls print
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/username/Documents/Dev/print/npm-debug.log
MacBook-Pro:print username$ 

```

**Comment by c316** [comment]
I am not sure exactly what is going on here, but I've summited a pull request to fix this. 

https://github.com/tojocky/node-printer/pull/156

Thanks
