### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by eduardoborges** [tojocky/node-printer#171]
I have this error, rebuild is not resolving.

```
Uncaught Error: The module '/Users/eduardoborges/Projetos/electron-es6-react/node_modules/printer/build/Release/node_printer.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eduardoborges/Projetos/electron-es6-react/node_modules/printer/lib/printer.js:10:22)
    at Object.<anonymous> (/Users/eduardoborges/Projetos/electron-es6-react/node_modules/printer/lib/printer.js:326:3)
```

someone have a solution?

**Comment by alexandre-le-borgne** [comment]
What command did you use for rebuild?

**Comment by tojocky** [comment]
I think the error is self explanatory: "was compiled against a different Node.js version using"
