### ISSUE TITLE
Anyone run node-printer successful on node 8 and npm 5?

### ISSUE THREAD

**Issue by taoyuan** [tojocky/node-printer#175]
Clone `node-printer` and run `npm install` on node `v8.1.2` and npm `5.0.3`. 

It looks like successful to run `npm install`: 
```
$ npm install
> printer@0.3.0 preinstall /Users/taoyuan/temp/node-printer
> npm install node-pre-gyp

npm WARN prefer global nw-gyp@0.12.4 should be installed with -g
npm WARN prefer global node-gyp@1.0.3 should be installed with -g
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN printer@0.3.0 No license field.

+ node-pre-gyp@0.6.36
added 458 packages in 96.976s

> printer@0.3.0 install /Users/taoyuan/temp/node-printer
> node-pre-gyp install --fallback-to-build

[printer] Success: "/Users/taoyuan/temp/node-printer/lib/node_printer.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN printer@0.3.0 No license field.

up to date in 99.146s
```
But it throws exception to run `node examples/getPrinters`:
```
$ node examples/getPrinters
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/Users/taoyuan/temp/node-printer/lib/node_printer.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taoyuan/temp/node-printer/lib/printer.js:10:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

It seams like NODE_MODULE_VERSION dose not match. But I did build `node-printer` on node v8. 

Has anyone succeeded on node v8?

**Comment by marksagal** [comment]
+1, Please update this module. I badly needed it also. :(

**Comment by taoyuan** [comment]
It can be installed on node 8.1.4 and above now.

**Comment by marf** [comment]
Hello, I have the same problem, I cannot use it with node v10

**Comment by esl-douglas** [comment]
Me too, same problem.
