### ISSUE TITLE
Error installing node printer

### ISSUE THREAD

**Issue by ebenKB** [tojocky/node-printer#197]
Please I need help with npm install printer. I am trying to install node printer for a  nodejs project, I have python 2.7 installed and am using msvs_version =2015. I am trying to install it in my project directory. 
 I get the following errors.

**F:\Eben.KB\Web Projects\NodePrinter>npm install printer --msvs_version=2015

> printer@0.2.2 install F:\Eben.KB\Web Projects\NodePrinter\node_modules\printer
> node-gyp rebuild

F:\Eben.KB\Web Projects\NodePrinter\node_modules\printer>if not defined npm_config_node_gyp (node "C:\Users\HUBKB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or Platf
ormToolset may be set to an invalid version number. [F:\Eben.KB\Web Projects\NodePrinter\node_modules\printer\build\node_printer.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [F:\Eben.KB\Web Projects\NodePrinter\node_modules\printer\build\node_printer.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\HUBKB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HUBKB\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Eben.KB\Web Projects\NodePrinter\node_modules\printer
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN nodeprinter@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! printer@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the printer@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.**

**Comment by lishichao1002** [comment]
+1
