### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by m0nsterzd** [tojocky/node-printer#211]
I am trying to install this on a debian 9 server and it is failing with 

> gyp: Call to 'cups-config --libs' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.0-3-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/printer/node_modules/node-printer
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

I have installed cups, node-gyp and libcups2-dev and still have the error.  Any ideas ?

**Comment by tojocky** [comment]
Did you run "cups-config --libs"?
