### ISSUE TITLE
this can npm install in raspberry pi ??

### ISSUE THREAD

**Issue by c941010623** [tojocky/node-printer#23]
i use npm install printer is not work

and

i download all file and use npm install also not work .....

how can i do ???

ps. i use in windows8 is ok ~~~but now i want use in raspberry pi (arm)
i use RASPBIAN Debian Wheezy os

**Comment by arathael** [comment]
I could reproduce the bug:
```
make: Entering directory '/home/pi/my-module/node_modules/printer/build'
  CXX(target) Release/obj.target/node_printer/src/node_printer_posix.o
../src/node_printer_posix.cc: In function ‘const FormatMapType& {anonymous}::getPrinterFormatMap()’:
../src/node_printer_posix.cc:47:46: error: ‘CUPS_FORMAT_JPEG’ was not declared in this scope
node_printer.target.mk:83: recipe for target 'Release/obj.target/node_printer/src/node_printer_posix.o' failed
make: *** [Release/obj.target/node_printer/src/node_printer_posix.o] Error 1
make: Leaving directory '/home/pi/my-module/node_modules/printer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/my-module/node_modules/printer
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! printer@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the printer@0.0.2 install script.
npm ERR! This is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "printer"
npm ERR! cwd /home/pi/my-module
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

I just installed Cups with apt-get, don't know how to check the version in cli, but web admin says CUPS 1.5.3

**Comment by arathael** [comment]
When installing with `$ npm install git+https://github.com/tojocky/node-printer.git` got no problems, guess 0.0.2 vs 0.0.3 was my thing.

**Comment by thejae** [comment]
For future references. CUPs dev libs installation on Raspbian, use this package

`sudo apt-get install libcups2 libcups2-dev`

**Comment by arathael** [comment]
It is failing to install again on ARM architecture, I guess it is because that arch is not planned in the grunt build.

**Comment by arathael** [comment]
I can make all the testing in the devices, can we make this work out again?
