### ISSUE TITLE
Uncaught Error: Could not call remote function 'getPrinters'

### ISSUE THREAD

**Issue by jzatarain** [tojocky/node-printer#231]
I'm trying to use this project with electron, but I'm getting this error in windows 10:
`C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:209 Uncaught Error: Could not call remote function 'getPrinters'. Check that the function signature is correct. Underlying error: Error on EnumJobsW: code: 6, message: The handle is invalid.

Error: Could not call remote function 'getPrinters'. Check that the function signature is correct. Underlying error: Error on EnumJobsW: code: 6, message: The handle is invalid.

    at callFunction (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at callFunction (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:209:30)
    at metaToValue (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:213:28)
    at Object.remoteMemberFunction (C:\Users\josue.zatarain\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:113:16)`

**Comment by jzatarain** [comment]
My code:
`var electron = require('electron');
        var remote = electron.remote;
        var api = remote.require('printer');
        console.log(api.getDefaultPrinterName());
        var printers = api.getPrinters();`

**Comment by ahoubouby** [comment]
any update about that's issue
