### ISSUE TITLE
NPM Packeges Printer Download Error

### ISSUE THREAD

**Issue by enesgezici** [tojocky/node-printer#262]
Cannot install printer packages NPM Packeges in Visual Studio

**Comment by enesgezici** [comment]
![image](https://user-images.githubusercontent.com/19204782/65334185-93bca000-dbca-11e9-9c5b-d88cb2cd5e3c.png)

**Comment by enesgezici** [comment]
I'm sending log records. We can reference you for problem solution. 
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'printer',
1 verbose cli   '--msvs_version=2017' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session 8f36eb1107f4cebe
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/printer 725ms (from cache)
8 silly pacote tag manifest for printer@latest fetched in 768ms
9 timing stage:loadCurrentTree Completed in 1920ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 9ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 248ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule printer@0.2.2 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 192ms
18 timing stage:loadIdealTree Completed in 566ms
19 silly currentTree NodeJSPrinterApp
19 silly currentTree +-- abbrev@1.1.1
19 silly currentTree +-- ajv@6.10.2
19 silly currentTree +-- ansi-regex@2.1.1
19 silly currentTree +-- aproba@1.2.0
19 silly currentTree +-- are-we-there-yet@1.1.5
19 silly currentTree +-- asn1@0.2.4
19 silly currentTree +-- assert-plus@1.0.0
19 silly currentTree +-- asynckit@0.4.0
19 silly currentTree +-- aws-sign2@0.7.0
19 silly currentTree +-- aws4@1.8.0
19 silly currentTree +-- balanced-match@1.0.0
19 silly currentTree +-- bcrypt-pbkdf@1.0.2
19 silly currentTree +-- brace-expansion@1.1.11
19 silly currentTree +-- caseless@0.12.0
19 silly currentTree +-- chownr@1.1.2
19 silly currentTree +-- code-point-at@1.1.0
19 silly currentTree +-- combined-stream@1.0.8
19 silly currentTree +-- concat-map@0.0.1
19 silly currentTree +-- console-control-strings@1.1.0
19 silly currentTree +-- core-util-is@1.0.2
19 silly currentTree +-- dashdash@1.14.1
19 silly currentTree +-- delayed-stream@1.0.0
19 silly currentTree +-- delegates@1.0.0
19 silly currentTree +-- ecc-jsbn@0.1.2
19 silly currentTree +-- env-paths@1.0.0
19 silly currentTree +-- extend@3.0.2
19 silly currentTree +-- extsprintf@1.3.0
19 silly currentTree +-- fast-deep-equal@2.0.1
19 silly currentTree +-- fast-json-stable-stringify@2.0.0
19 silly currentTree +-- forever-agent@0.6.1
19 silly currentTree +-- form-data@2.3.3
19 silly currentTree +-- fs-minipass@1.2.7
19 silly currentTree +-- fs.realpath@1.0.0
19 silly currentTree +-- gauge@2.7.4
19 silly currentTree +-- getpass@0.1.7
19 silly currentTree +-- glob@7.1.4
19 silly currentTree +-- graceful-fs@4.2.2
19 silly currentTree +-- har-schema@2.0.0
19 silly currentTree +-- har-validator@5.1.3
19 silly currentTree +-- has-unicode@2.0.1
19 silly currentTree +-- http-signature@1.2.0
19 silly currentTree +-- inflight@1.0.6
19 silly currentTree +-- inherits@2.0.4
19 silly currentTree +-- is-fullwidth-code-point@1.0.0
19 silly currentTree +-- is-typedarray@1.0.0
19 silly currentTree +-- isarray@1.0.0
19 silly currentTree +-- isexe@2.0.0
19 silly currentTree +-- isstream@0.1.2
19 silly currentTree +-- jsbn@0.1.1
19 silly currentTree +-- json-schema-traverse@0.4.1
19 silly currentTree +-- json-schema@0.2.3
19 silly currentTree +-- json-stringify-safe@5.0.1
19 silly currentTree +-- jsprim@1.4.1
19 silly currentTree +-- mime-db@1.40.0
19 silly currentTree +-- mime-types@2.1.24
19 silly currentTree +-- minimatch@3.0.4
19 silly currentTree +-- minimist@0.0.8
19 silly currentTree +-- minipass@2.6.5
19 silly currentTree +-- minizlib@1.2.2
19 silly currentTree +-- mkdirp@0.5.1
19 silly currentTree +-- node-gyp@5.0.3
19 silly currentTree +-- node-printer@1.0.4
19 silly currentTree +-- nopt@3.0.6
19 silly currentTree +-- npmlog@4.1.2
19 silly currentTree +-- number-is-nan@1.0.1
19 silly currentTree +-- oauth-sign@0.9.0
19 silly currentTree +-- object-assign@4.1.1
19 silly currentTree +-- once@1.4.0
19 silly currentTree +-- path-is-absolute@1.0.1
19 silly currentTree +-- performance-now@2.1.0
19 silly currentTree +-- process-nextick-args@2.0.1
19 silly currentTree +-- psl@1.4.0
19 silly currentTree +-- punycode@2.1.1
19 silly currentTree +-- qs@6.5.2
19 silly currentTree +-- readable-stream@2.3.6
19 silly currentTree +-- request@2.88.0
19 silly currentTree +-- rimraf@2.7.1
19 silly currentTree +-- safe-buffer@5.1.2
19 silly currentTree +-- safer-buffer@2.1.2
19 silly currentTree +-- semver@5.3.0
19 silly currentTree +-- set-blocking@2.0.0
19 silly currentTree +-- signal-exit@3.0.2
19 silly currentTree +-- sshpk@1.16.1
19 silly currentTree +-- string_decoder@1.1.1
19 silly currentTree +-- string-width@1.0.2
19 silly currentTree +-- strip-ansi@3.0.1
19 silly currentTree +-- tar@4.4.11
19 silly currentTree +-- tough-cookie@2.4.3
19 silly currentTree | `-- punycode@1.4.1
19 silly currentTree +-- tunnel-agent@0.6.0
19 silly currentTree +-- tweetnacl@0.14.5
19 silly currentTree +-- underscore@1.9.1
19 silly currentTree +-- uri-js@4.2.2
19 silly currentTree +-- util-deprecate@1.0.2
19 silly currentTree +-- uuid@3.3.3
19 silly currentTree +-- verror@1.10.0
19 silly currentTree +-- which@1.3.1
19 silly currentTree +-- wide-align@1.1.3
19 silly currentTree +-- wrappy@1.0.2
19 silly currentTree `-- yallist@3.0.3
20 silly idealTree NodeJSPrinterApp
20 silly idealTree +-- abbrev@1.1.1
20 silly idealTree +-- ajv@6.10.2
20 silly idealTree +-- ansi-regex@2.1.1
20 silly idealTree +-- aproba@1.2.0
20 silly idealTree +-- are-we-there-yet@1.1.5
20 silly idealTree +-- asn1@0.2.4
20 silly idealTree +-- assert-plus@1.0.0
20 silly idealTree +-- asynckit@0.4.0
20 silly idealTree +-- aws-sign2@0.7.0
20 silly idealTree +-- aws4@1.8.0
20 silly idealTree +-- balanced-match@1.0.0
20 silly idealTree +-- bcrypt-pbkdf@1.0.2
20 silly idealTree +-- brace-expansion@1.1.11
20 silly idealTree +-- caseless@0.12.0
20 silly idealTree +-- chownr@1.1.2
20 silly idealTree +-- code-point-at@1.1.0
20 silly idealTree +-- combined-stream@1.0.8
20 silly idealTree +-- concat-map@0.0.1
20 silly idealTree +-- console-control-strings@1.1.0
20 silly idealTree +-- core-util-is@1.0.2
20 silly idealTree +-- dashdash@1.14.1
20 silly idealTree +-- delayed-stream@1.0.0
20 silly idealTree +-- delegates@1.0.0
20 silly idealTree +-- ecc-jsbn@0.1.2
20 silly idealTree +-- env-paths@1.0.0
20 silly idealTree +-- extend@3.0.2
20 silly idealTree +-- extsprintf@1.3.0
20 silly idealTree +-- fast-deep-equal@2.0.1
20 silly idealTree +-- fast-json-stable-stringify@2.0.0
20 silly idealTree +-- forever-agent@0.6.1
20 silly idealTree +-- form-data@2.3.3
20 silly idealTree +-- fs-minipass@1.2.7
20 silly idealTree +-- fs.realpath@1.0.0
20 silly idealTree +-- gauge@2.7.4
20 silly idealTree +-- getpass@0.1.7
20 silly idealTree +-- glob@7.1.4
20 silly idealTree +-- graceful-fs@4.2.2
20 silly idealTree +-- har-schema@2.0.0
20 silly idealTree +-- har-validator@5.1.3
20 silly idealTree +-- has-unicode@2.0.1
20 silly idealTree +-- http-signature@1.2.0
20 silly idealTree +-- inflight@1.0.6
20 silly idealTree +-- inherits@2.0.4
20 silly idealTree +-- is-fullwidth-code-point@1.0.0
20 silly idealTree +-- is-typedarray@1.0.0
20 silly idealTree +-- isarray@1.0.0
20 silly idealTree +-- isexe@2.0.0
20 silly idealTree +-- isstream@0.1.2
20 silly idealTree +-- jsbn@0.1.1
20 silly idealTree +-- json-schema-traverse@0.4.1
20 silly idealTree +-- json-schema@0.2.3
20 silly idealTree +-- json-stringify-safe@5.0.1
20 silly idealTree +-- jsprim@1.4.1
20 silly idealTree +-- mime-db@1.40.0
20 silly idealTree +-- mime-types@2.1.24
20 silly idealTree +-- minimatch@3.0.4
20 silly idealTree +-- minimist@0.0.8
20 silly idealTree +-- minipass@2.6.5
20 silly idealTree +-- minizlib@1.2.2
20 silly idealTree +-- mkdirp@0.5.1
20 silly idealTree +-- node-gyp@5.0.3
20 silly idealTree +-- node-printer@1.0.4
20 silly idealTree +-- nopt@3.0.6
20 silly idealTree +-- npmlog@4.1.2
20 silly idealTree +-- number-is-nan@1.0.1
20 silly idealTree +-- oauth-sign@0.9.0
20 silly idealTree +-- object-assign@4.1.1
20 silly idealTree +-- once@1.4.0
20 silly idealTree +-- path-is-absolute@1.0.1
20 silly idealTree +-- performance-now@2.1.0
20 silly idealTree +-- printer@0.2.2
20 silly idealTree +-- process-nextick-args@2.0.1
20 silly idealTree +-- psl@1.4.0
20 silly idealTree +-- punycode@2.1.1
20 silly idealTree +-- qs@6.5.2
20 silly idealTree +-- readable-stream@2.3.6
20 silly idealTree +-- request@2.88.0
20 silly idealTree +-- rimraf@2.7.1
20 silly idealTree +-- safe-buffer@5.1.2
20 silly idealTree +-- safer-buffer@2.1.2
20 silly idealTree +-- semver@5.3.0
20 silly idealTree +-- set-blocking@2.0.0
20 silly idealTree +-- signal-exit@3.0.2
20 silly idealTree +-- sshpk@1.16.1
20 silly idealTree +-- string_decoder@1.1.1
20 silly idealTree +-- string-width@1.0.2
20 silly idealTree +-- strip-ansi@3.0.1
20 silly idealTree +-- tar@4.4.11
20 silly idealTree +-- tough-cookie@2.4.3
20 silly idealTree | `-- punycode@1.4.1
20 silly idealTree +-- tunnel-agent@0.6.0
20 silly idealTree +-- tweetnacl@0.14.5
20 silly idealTree +-- underscore@1.9.1
20 silly idealTree +-- uri-js@4.2.2
20 silly idealTree +-- util-deprecate@1.0.2
20 silly idealTree +-- uuid@3.3.3
20 silly idealTree +-- verror@1.10.0
20 silly idealTree +-- which@1.3.1
20 silly idealTree +-- wide-align@1.1.3
20 silly idealTree +-- wrappy@1.0.2
20 silly idealTree `-- yallist@3.0.3
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 35ms
23 silly diffTrees action count 1
24 silly diffTrees add printer@0.2.2
25 silly decomposeActions action count 8
26 silly decomposeActions fetch printer@0.2.2
27 silly decomposeActions extract printer@0.2.2
28 silly decomposeActions preinstall printer@0.2.2
29 silly decomposeActions build printer@0.2.2
30 silly decomposeActions install printer@0.2.2
31 silly decomposeActions postinstall printer@0.2.2
32 silly decomposeActions finalize printer@0.2.2
33 silly decomposeActions refresh-package-json printer@0.2.2
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir C:\Users\egezici\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
37 timing audit compress Completed in 5ms
38 info audit Submitting payload of 7110bytes
39 verbose lock using C:\Users\egezici\AppData\Roaming\npm-cache\_locks\staging-94a2f3034316b118.lock for C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\.staging
40 silly doParallel extract 1
41 silly extract printer@0.2.2
42 silly tarball trying printer@latest by hash: sha1-gwuPXJe5f9m0ZNT04QXUMzd5IpY=
43 silly extract printer@latest extracted to C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\.staging\printer-79630506 (112ms)
44 timing action:extract Completed in 118ms
45 silly doReverseSerial unbuild 8
46 silly doSerial remove 8
47 silly doSerial move 8
48 silly doSerial finalize 8
49 silly finalize C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\printer
50 timing action:finalize Completed in 6ms
51 silly doParallel refresh-package-json 1
52 silly refresh-package-json C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\printer
53 timing action:refresh-package-json Completed in 16ms
54 silly doParallel preinstall 1
55 silly preinstall printer@0.2.2
56 info lifecycle printer@0.2.2~preinstall: printer@0.2.2
57 timing action:preinstall Completed in 2ms
58 silly doSerial build 8
59 silly build printer@0.2.2
60 info linkStuff printer@0.2.2
61 silly linkStuff printer@0.2.2 has C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules as its parent node_modules
62 timing action:build Completed in 1ms
63 silly doSerial global-link 8
64 silly doParallel update-linked 0
65 silly doSerial install 8
66 silly install printer@0.2.2
67 info lifecycle printer@0.2.2~install: printer@0.2.2
68 verbose lifecycle printer@0.2.2~install: unsafe-perm in lifecycle true
69 verbose lifecycle printer@0.2.2~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\printer\node_modules\.bin;C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\PuTTY\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\dotnet\;C:\Users\egezici\AppData\Local\Microsoft\WindowsApps;C:\Users\egezici\AppData\Local\atom\bin;C:\Users\egezici\AppData\Roaming\npm;C:\Program Files\JetBrains\WebStorm 2019.1.1\bin;C:\Users\egezici\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\egezici\AppData\Local\Programs\Fiddler
70 verbose lifecycle printer@0.2.2~install: CWD: C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\printer
71 silly lifecycle printer@0.2.2~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
72 silly lifecycle printer@0.2.2~install: Returned: code: 1  signal: null
73 info lifecycle printer@0.2.2~install: Failed to exec install script
74 timing action:install Completed in 805ms
75 verbose unlock done using C:\Users\egezici\AppData\Roaming\npm-cache\_locks\staging-94a2f3034316b118.lock for C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\node_modules\.staging
76 timing stage:rollbackFailedOptional Completed in 40ms
77 timing stage:runTopLevelLifecycles Completed in 3724ms
78 silly saveTree NodeJSPrinterApp
78 silly saveTree +-- abbrev@1.1.1
78 silly saveTree +-- ajv@6.10.2
78 silly saveTree | +-- fast-deep-equal@2.0.1
78 silly saveTree | +-- fast-json-stable-stringify@2.0.0
78 silly saveTree | +-- json-schema-traverse@0.4.1
78 silly saveTree | `-- uri-js@4.2.2
78 silly saveTree |   `-- punycode@2.1.1
78 silly saveTree +-- ansi-regex@2.1.1
78 silly saveTree +-- aproba@1.2.0
78 silly saveTree +-- are-we-there-yet@1.1.5
78 silly saveTree | +-- delegates@1.0.0
78 silly saveTree | `-- readable-stream@2.3.6
78 silly saveTree |   +-- core-util-is@1.0.2
78 silly saveTree |   +-- inherits@2.0.4
78 silly saveTree |   +-- isarray@1.0.0
78 silly saveTree |   +-- process-nextick-args@2.0.1
78 silly saveTree |   +-- safe-buffer@5.1.2
78 silly saveTree |   +-- string_decoder@1.1.1
78 silly saveTree |   `-- util-deprecate@1.0.2
78 silly saveTree +-- asn1@0.2.4
78 silly saveTree | `-- safer-buffer@2.1.2
78 silly saveTree +-- assert-plus@1.0.0
78 silly saveTree +-- asynckit@0.4.0
78 silly saveTree +-- aws-sign2@0.7.0
78 silly saveTree +-- aws4@1.8.0
78 silly saveTree +-- balanced-match@1.0.0
78 silly saveTree +-- bcrypt-pbkdf@1.0.2
78 silly saveTree | `-- tweetnacl@0.14.5
78 silly saveTree +-- brace-expansion@1.1.11
78 silly saveTree | `-- concat-map@0.0.1
78 silly saveTree +-- caseless@0.12.0
78 silly saveTree +-- chownr@1.1.2
78 silly saveTree +-- code-point-at@1.1.0
78 silly saveTree +-- combined-stream@1.0.8
78 silly saveTree | `-- delayed-stream@1.0.0
78 silly saveTree +-- concat-map@0.0.1
78 silly saveTree +-- console-control-strings@1.1.0
78 silly saveTree +-- core-util-is@1.0.2
78 silly saveTree +-- dashdash@1.14.1
78 silly saveTree +-- delayed-stream@1.0.0
78 silly saveTree +-- delegates@1.0.0
78 silly saveTree +-- ecc-jsbn@0.1.2
78 silly saveTree | `-- jsbn@0.1.1
78 silly saveTree +-- env-paths@1.0.0
78 silly saveTree +-- extend@3.0.2
78 silly saveTree +-- extsprintf@1.3.0
78 silly saveTree +-- fast-deep-equal@2.0.1
78 silly saveTree +-- fast-json-stable-stringify@2.0.0
78 silly saveTree +-- forever-agent@0.6.1
78 silly saveTree +-- form-data@2.3.3
78 silly saveTree | `-- mime-types@2.1.24
78 silly saveTree |   `-- mime-db@1.40.0
78 silly saveTree +-- fs-minipass@1.2.7
78 silly saveTree | `-- minipass@2.6.5
78 silly saveTree |   `-- yallist@3.0.3
78 silly saveTree +-- fs.realpath@1.0.0
78 silly saveTree +-- gauge@2.7.4
78 silly saveTree | +-- has-unicode@2.0.1
78 silly saveTree | +-- object-assign@4.1.1
78 silly saveTree | +-- signal-exit@3.0.2
78 silly saveTree | +-- string-width@1.0.2
78 silly saveTree | | +-- is-fullwidth-code-point@1.0.0
78 silly saveTree | | | `-- number-is-nan@1.0.1
78 silly saveTree | | `-- strip-ansi@3.0.1
78 silly saveTree | +-- strip-ansi@3.0.1
78 silly saveTree | `-- wide-align@1.1.3
78 silly saveTree +-- getpass@0.1.7
78 silly saveTree +-- glob@7.1.4
78 silly saveTree | +-- inflight@1.0.6
78 silly saveTree | | +-- once@1.4.0
78 silly saveTree | | | `-- wrappy@1.0.2
78 silly saveTree | | `-- wrappy@1.0.2
78 silly saveTree | +-- minimatch@3.0.4
78 silly saveTree | +-- once@1.4.0
78 silly saveTree | `-- path-is-absolute@1.0.1
78 silly saveTree +-- graceful-fs@4.2.2
78 silly saveTree +-- har-schema@2.0.0
78 silly saveTree +-- har-validator@5.1.3
78 silly saveTree +-- has-unicode@2.0.1
78 silly saveTree +-- http-signature@1.2.0
78 silly saveTree | +-- jsprim@1.4.1
78 silly saveTree | | +-- json-schema@0.2.3
78 silly saveTree | | `-- verror@1.10.0
78 silly saveTree | `-- sshpk@1.16.1
78 silly saveTree +-- inflight@1.0.6
78 silly saveTree +-- inherits@2.0.4
78 silly saveTree +-- is-fullwidth-code-point@1.0.0
78 silly saveTree +-- is-typedarray@1.0.0
78 silly saveTree +-- isarray@1.0.0
78 silly saveTree +-- isexe@2.0.0
78 silly saveTree +-- isstream@0.1.2
78 silly saveTree +-- jsbn@0.1.1
78 silly saveTree +-- json-schema-traverse@0.4.1
78 silly saveTree +-- json-schema@0.2.3
78 silly saveTree +-- json-stringify-safe@5.0.1
78 silly saveTree +-- jsprim@1.4.1
78 silly saveTree +-- mime-db@1.40.0
78 silly saveTree +-- mime-types@2.1.24
78 silly saveTree +-- minimatch@3.0.4
78 silly saveTree +-- minimist@0.0.8
78 silly saveTree +-- minipass@2.6.5
78 silly saveTree +-- minizlib@1.2.2
78 silly saveTree +-- mkdirp@0.5.1
78 silly saveTree +-- node-gyp@5.0.3
78 silly saveTree | +-- nopt@3.0.6
78 silly saveTree | +-- npmlog@4.1.2
78 silly saveTree | | `-- set-blocking@2.0.0
78 silly saveTree | +-- request@2.88.0
78 silly saveTree | | +-- oauth-sign@0.9.0
78 silly saveTree | | +-- performance-now@2.1.0
78 silly saveTree | | +-- qs@6.5.2
78 silly saveTree | | +-- tough-cookie@2.4.3
78 silly saveTree | | | +-- psl@1.4.0
78 silly saveTree | | | `-- punycode@1.4.1
78 silly saveTree | | +-- tunnel-agent@0.6.0
78 silly saveTree | | `-- uuid@3.3.3
78 silly saveTree | +-- rimraf@2.7.1
78 silly saveTree | +-- semver@5.3.0
78 silly saveTree | +-- tar@4.4.11
78 silly saveTree | `-- which@1.3.1
78 silly saveTree +-- node-printer@1.0.4
78 silly saveTree | `-- underscore@1.9.1
78 silly saveTree +-- nopt@3.0.6
78 silly saveTree +-- npmlog@4.1.2
78 silly saveTree +-- number-is-nan@1.0.1
78 silly saveTree +-- oauth-sign@0.9.0
78 silly saveTree +-- object-assign@4.1.1
78 silly saveTree +-- once@1.4.0
78 silly saveTree +-- path-is-absolute@1.0.1
78 silly saveTree +-- performance-now@2.1.0
78 silly saveTree +-- printer@0.2.2
78 silly saveTree +-- process-nextick-args@2.0.1
78 silly saveTree +-- psl@1.4.0
78 silly saveTree +-- punycode@2.1.1
78 silly saveTree +-- qs@6.5.2
78 silly saveTree +-- readable-stream@2.3.6
78 silly saveTree +-- request@2.88.0
78 silly saveTree +-- rimraf@2.7.1
78 silly saveTree +-- safe-buffer@5.1.2
78 silly saveTree +-- safer-buffer@2.1.2
78 silly saveTree +-- semver@5.3.0
78 silly saveTree +-- set-blocking@2.0.0
78 silly saveTree +-- signal-exit@3.0.2
78 silly saveTree +-- sshpk@1.16.1
78 silly saveTree +-- string_decoder@1.1.1
78 silly saveTree +-- string-width@1.0.2
78 silly saveTree +-- strip-ansi@3.0.1
78 silly saveTree +-- tar@4.4.11
78 silly saveTree +-- tough-cookie@2.4.3
78 silly saveTree +-- tunnel-agent@0.6.0
78 silly saveTree +-- tweetnacl@0.14.5
78 silly saveTree +-- underscore@1.9.1
78 silly saveTree +-- uri-js@4.2.2
78 silly saveTree +-- util-deprecate@1.0.2
78 silly saveTree +-- uuid@3.3.3
78 silly saveTree +-- verror@1.10.0
78 silly saveTree +-- which@1.3.1
78 silly saveTree +-- wide-align@1.1.3
78 silly saveTree +-- wrappy@1.0.2
78 silly saveTree `-- yallist@3.0.3
79 warn enoent ENOENT: no such file or directory, open 'C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp\package.json'
80 verbose enoent This is related to npm not being able to find a file.
81 warn NodeJSPrinterApp No description
82 warn NodeJSPrinterApp No repository field.
83 warn NodeJSPrinterApp No README data
84 warn NodeJSPrinterApp No license field.
85 verbose stack Error: printer@0.2.2 install: `node-gyp rebuild`
85 verbose stack Exit status 1
85 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
85 verbose stack     at EventEmitter.emit (events.js:189:13)
85 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
85 verbose stack     at ChildProcess.emit (events.js:189:13)
85 verbose stack     at maybeClose (internal/child_process.js:970:16)
85 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
86 verbose pkgid printer@0.2.2
87 verbose cwd C:\Users\egezici\Paylaşılan Klasör\GCAKIROGLU\NodeJSPrinterApp\NodeJSPrinterApp
88 verbose Windows_NT 10.0.17134
89 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer" "--msvs_version=2017"
90 verbose node v10.15.3
91 verbose npm  v6.4.1
92 error code ELIFECYCLE
93 error errno 1
94 error printer@0.2.2 install: `node-gyp rebuild`
94 error Exit status 1
95 error Failed at the printer@0.2.2 install script.
95 error This is probably not a problem with npm. There is likely additional logging output above.
96 verbose exit [ 1, true ]
`

**Comment by dph5199278** [comment]
1. --msvs_version=2017  printer module could not support VS2017 and above.( In my test)

I use cli "npm install printer --msvs_version=2015 --target=10.15.3" to install.
Maybe you should focus in "Other npm arguments", input "--target=10.15.3".

Good lucky

**Comment by enesgezici** [comment]
Hello, Thanks for the response. I'm using Visual Studio 2017.  Can I run "npm install printer - msvs_version = 2015 --target = 10.15.3" 

I'm asking why. Because in the command you send  msvs_version =2015 ? 

Thank you so much.
