### ISSUE TITLE
window 10npm run build:dir error on electron-vue

### ISSUE THREAD

**Issue by fxh615** [tojocky/node-printer#285]
npm run dev works fine ,
npm run build:dir error

node: v8.17.0
electron 2.0.19
vs 2019
win32 x64

error info
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tojocky/node-printer/releases/download/0.4.0/node_printer-v0.4.0-electron-v2.0-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for printer@0.4.0 and electron@2.0.18 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by fxh615** [comment]
my macOS  works all fine

**Comment by fxh615** [comment]
OKAY  take it away `electron-builder`

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> @thiagoelg/node-printer@0.5.2 install G:\works\smart-printer\node_modules\@thiagoelg\node-printer
> prebuild-install || node-gyp rebuild


> bufferutil@4.0.1 install G:\works\smart-printer\node_modules\bufferutil
> node-gyp-build


> printer@0.4.0 preinstall G:\works\smart-printer\node_modules\printer
> npm install node-gyp node-pre-gyp

+ node-pre-gyp@0.14.0
+ node-gyp@6.1.0
updated 2 packages in 5.234s

> printer@0.4.0 install G:\works\smart-printer\node_modules\printer
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\works\smart-printer\node_modules\printer\lib\node_printer.node --module_name=node_printer --module_path=G:\works\smart-printer\node_modules\printer\lib --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v2.0 --msvs_version=2019' (1)

Error output:
npm WARN printer@0.4.0 No license field.

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tojocky/node-printer/releases/download/0.4.0/node_printer-v0.4.0-electron-v2.0-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for printer@0.4.0 and electron@2.0.18 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 status code downloading arm64 iojs.lib
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:335:22)  
gyp ERR! stack     at Request.emit (events.js:323:22)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)gyp ERR! stack     at ClientRequest.emit (events.js:311:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:476:22)
gyp ERR! stack     at TLSSocket.emit (events.js:311:20)
gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\works\\smart-printer\\node_modules\\printer\\lib\\node_printer.node" "--module_name=node_printer" "--module_path=G:\\works\\smart-printer\\node_modules\\printer\\lib" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v2.0" "--msvs_version=2019"
gyp ERR! cwd G:\works\smart-printer\node_modules\printer
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\works\smart-printer\node_modules\printer\lib\node_printer.node --module_name=node_printer --module_path=G:\works\smart-printer\node_modules\printer\lib --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v2.0 --msvs_version=2019' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\works\smart-printer\node_modules\printer\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\works\\smart-printer\\node_modules\\printer\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd G:\works\smart-printer\node_modules\printer
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! printer@0.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the printer@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ThinkPad\AppData\Roaming\npm-cache\_logs\2020-03-31T01_20_36_579Z-debug.log

    at ChildProcess.<anonymous> (G:\works\smart-printer\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
From previous event:
    at _rebuild (G:\works\smart-printer\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (G:\works\smart-printer\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at G:\works\smart-printer\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at _installOrRebuild (G:\works\smart-printer\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (G:\works\smart-printer\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:470:70)
    at G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:396:24)
    at G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at G:\works\smart-printer\node_modules\graceful-fs\graceful-fs.js:136:16
    at G:\works\smart-printer\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:154:23)
From previous event:
    at Packager._build (G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:335:133)
    at G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Packager.build (G:\works\smart-printer\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (G:\works\smart-printer\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (G:\works\smart-printer\node_modules\electron-builder\src\builder.ts:228:10)
    at G:\works\smart-printer\node_modules\electron-builder\src\cli\cli.ts:49:19
