### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by Kekec852** [tojocky/node-printer#288]
I have issue with the package.

Node version: 13.13.0
OS: Linux Mint 19.3 Cinnamon / Debian 10.3
Command: npm i  -s printer

Then running:
```typescript
//@ts-ignore
import printer from 'printer';

console.log(printer.getDefaultPrinterName());
```
I get:

```
user@test:/opt/test/backend$ ts-node
> //@ts-ignore
'use strict'
> import printer from 'printer';
{}
>
undefined
> console.log(printer.getDefaultPrinterName());
internal/modules/cjs/loader.js:1173
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Uncaught:
Error: /opt/test/backend/node_modules/printer/lib/node_printer.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/test/backend/node_modules/printer/lib/printer.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
> 
```

If i run `npm install printer --build-from-source=node_printer --update-binary` on Mint things starts to work on Debian i get error `gyp: Call to 'cups-config --libs' returned exit status 0 while in binding.gyp. while trying to load binding.gyp` even i cups stuff is installed.

**Comment by Kekec852** [comment]
I'm on to something as on my other installation of Debian it works using `npm install printer --build-from-source=node_printer --update-binary` command. 

I dag a bit deeper and `cups-config --libs` will return error if you don't have correct setup of local!

**Comment by kenywan910** [comment]
thanks! it helps me a lot.
