### ISSUE TITLE
Not compiling with MacOS 10.15.6, Electron 10.1.3, Node 12.19.0

### ISSUE THREAD

**Issue by alfreddagenais** [tojocky/node-printer#298]
I got this error when I try to run my Electron app  : 

```
../src/node_printer_posix.cc:76:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "id", V8_VALUE_NEW(Number, job->id));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:77:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "name", V8_STRING_NEW_UTF8(job->title));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:78:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "printerName", V8_STRING_NEW_UTF8(job->dest));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:79:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "user", V8_STRING_NEW_UTF8(job->user));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
                                                                                                                                                                                3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
⠙ Preparing native dependencies: 3 / 4../src/node_printer_posix.cc:92:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "format", V8_STRING_NEW_UTF8(job_format.c_str()));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:93:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "priority", V8_VALUE_NEW(Number, job->priority));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:94:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "size", V8_VALUE_NEW(Number, job->size));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:101:17: error: no matching member function for call to 'Set'
                MY_NODE_SET_OBJECT(result_printer_job_status, i_status++, V8_STRING_NEW_UTF8(itStatus->first.c_str()));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:111:13: error: no matching member function for call to 'Set'
            MY_NODE_SET_OBJECT(result_printer_job_status, i_status++, V8_STRING_NEW_UTF8(s.str().c_str()));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:114:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "status", result_printer_job_status);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:123:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "completedTime", Nan::New<v8::Date>(completedTime).ToLocalChecked());
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:124:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "creationTime", Nan::New<v8::Date>(creationTime).ToLocalChecked());
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:125:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer_job, "processingTime", Nan::New<v8::Date>(processingTime).ToLocalChecked());
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:148:17: error: no matching member function for call to 'Set'
                MY_NODE_SET_OBJECT_PROP(ppd_suboptions, choice->choice, V8_VALUE_NEW(Boolean, static_cast<bool>(choice->marked)));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:151:13: error: no matching member function for call to 'Set'
            MY_NODE_SET_OBJECT_PROP(ppd_options, option->keyword, ppd_suboptions);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:205:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer, "name", V8_STRING_NEW_UTF8(printer->name));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:206:9: error: no matching member function for call to 'Set'
        MY_NODE_SET_OBJECT_PROP(result_printer, "isDefault", V8_VALUE_NEW(Boolean, static_cast<bool>(printer->is_default)));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:210:13: error: no matching member function for call to 'Set'
            MY_NODE_SET_OBJECT_PROP(result_printer, "instance", V8_STRING_NEW_UTF8(printer->instance));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/node_printer_posix.cc:218:13: error: no matching member function for call to 'Set'
            MY_NODE_SET_OBJECT_PROP(result_printer_options, dest_option->name, V8_STRING_NEW_UTF8(dest_option->value));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:14:53: note: expanded from macro 'MY_NODE_SET_OBJECT_PROP'
#  define MY_NODE_SET_OBJECT_PROP(object, id, prop) MY_NODE_SET_OBJECT(object, V8_STRING_NEW_UTF8(id), prop)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/macros.hh:13:56: note: expanded from macro 'MY_NODE_SET_OBJECT'
#  define MY_NODE_SET_OBJECT(object, id, prop) object->Set(id, prop)
                                               ~~~~~~~~^~~
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3685:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
borne-poc1/node_modules/printer/10.1.3/include/node/v8.h:3688:37: note: candidate function not viable: requires 3 arguments, but
      2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_printer/src/node_printer_posix.o] Error 1
✖ Preparing native dependencies: 3 / 4

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild 'borne-poc1/node_modules/printer'.
Error: `make` failed with exit code: 2


Error: node-gyp failed to rebuild 'borne-poc1/node_modules/printer'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (borne-poc1/node_modules/electron-rebuild/src/module-rebuilder.ts:231:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! connectngo-borne-oriel@1.0.1 start: `electron-forge start "dev"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the connectngo-borne-oriel@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alfreddagenais/.npm/_logs/2020-10-15T20_30_40_801Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! connectngo-borne-oriel@1.0.1 start:dev: `npm run build:dev && npm run start -- dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the connectngo-borne-oriel@1.0.1 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: /Users/alfreddagenais/.npm/_logs/2020-10-15T20_30_40_801Z-debug.log
```

MacOS 10.15.6
Electron 10.1.3
Node 12.19.0
"@electron-forge/cli": "^6.0.0-beta.53",

I run my app to do : 
```bash
npx electron-forge start
```

Have you an idea how to solve this? Thanks

**Comment by Rish-XO** [comment]
hey, iam working on to create a electron tray app, for printing .  iam currently using node 18, and this package is not installing,

and even when i install it through node 14, my app is throwing this error = 
$ npm start

> printease@1.0.0 start D:\tongadive\printease
> electron .


App threw an error during load
Error: \\?\D:\tongadive\printease\node_modules\printer\lib\node_printer.node is not a valid Win32 application.
\\?\D:\tongadive\printease\node_modules\printer\lib\node_printer.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2559)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\tongadive\printease\node_modules\printer\lib\printer.js:10:22)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    
    
    if you found any solutions , help me
