### ISSUE TITLE
node-webkit build windows

### ISSUE THREAD

**Issue by Phoscur** [tojocky/node-printer#76]
I've tried building the with the latest version and with 0.9.2 as a nw-gyp target
```
Uncaught node.js Error 

Error: no error
    ...\node_modules\printer\build\Release\node_printer.node
    at Error (native)
    at Module.load (module.js:354:32)
```
That's the error I'm getting when I run `nw . ´

I'm using nodejs v.0.12.4(x86 only, v.0.12.5 no luck) on Windows 7 x64.

**Comment by rurigk** [comment]
what is your version of nwjs

**Comment by tojocky** [comment]
Could you please retry?

**Comment by Sangd8** [comment]
Hi, i have same issue too.
Here my error message
```
Uncaught Error: Module version mismatch. Expected 43, got 46.                  module.js:346
``` 
Command:
```
nwbuild -v 0.12.0 -r ./
```
and printer node module
```
var printer = require("printer");
```
Once i remove that line, the code works fine.
i'm using node 4.1.2, Windows 10 x64,

**Comment by Sangd8** [comment]
Ok, i finally can make it works now. I tried to rebuild the nw-gyp of printer with nwjs 0.12.0
```
$ npm install -g nw-gyp
$ cd node_modules/printer
$ nw-gyp configure --target=0.12.0
$ nw-gyp build
```
Now it works like charm.

**Comment by fanjg** [comment]
I can not install printer  by excuting  npm install printer.
And error message:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\setup\\nodejs\\node.exe',
1 verbose cli   'D:\\setup\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'printer' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose install initial load of d:\work\work\dianqu\nodedemo\nwprinter\package.json
5 verbose stack Error: Invalid name: "printer demo"
5 verbose stack     at ensureValidName (D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:331:15)
5 verbose stack     at Object.module.exports.fixNameField (D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:210:5)
5 verbose stack     at D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
5 verbose stack     at final (D:\setup\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:338:5)
5 verbose stack     at then (D:\setup\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
5 verbose stack     at ReadFileContext.<anonymous> (D:\setup\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
5 verbose stack     at ReadFileContext.callback (D:\setup\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
6 verbose cwd d:\work\work\dianqu\nodedemo\nwprinter
7 error Windows_NT 6.1.7601
8 error argv "D:\\setup\\nodejs\\node.exe" "D:\\setup\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer"
9 error node v4.2.3
10 error npm  v2.14.7
11 error Invalid name: "printer demo"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by Phoscur** [comment]
@Sangd8 With which combination of versions and commands did you solve this?
I'm getting

    Error: Module version mismatch. Expected 14, got 43.

Tried:
     nw-gyp rebuild --target=0.12.0 --msvs_version=2013
and 
    nw-gyp rebuild --target=0.12.3 --msvs_version=2013

I have nw v0.12.3 and nodejs v4.2.3 installed. (Windows 7 x64).
node-printer 0.2.1

**Comment by Phoscur** [comment]
I have upgraded msvs_version to 2015 and built and rebuild the module properly. I'm also getting the version mismatch using an older nodejs version like v.0.12.

I'm getting the old error (threadstart) when I try building it with the newest node-webkit (--target=0.13.0-beta3).

???

**Comment by Phoscur** [comment]
Finally, got a working build after downgrading node to v0.12, npm to v2, and node-webkit to v0.11.3.

    nw-gyp rebuild --target=0.11.3
