### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by gberthalon** [tojocky/node-printer#90]
Hi 
npm install fail with :
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'inflight'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:338:15)
gyp ERR! stack     at Function.Module._load (module.js:280:25)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! stack     at require (module.js:380:17)
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\n
pm\node_modules\node-gyp\node_modules\glob\glob.js:57:16)
gyp ERR! stack     at Module._compile (module.js:456:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! stack     at Function.Module._load (module.js:312:12)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! System Windows_NT 6.0.6002
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"

An idea?

**Comment by gberthalon** [comment]
OK >>
my version of node is 1.10.26
I've installed 1.12
and : 
> npm install printer
reinstall node 1.10.26
go in printer directory and :
> node-gyp rebuild
