### ISSUE TITLE
Building in ARM

### ISSUE THREAD

**Issue by arathael** [tojocky/node-printer#91]
Hi I'm using node `v4.1.1`, npm `v3.1.1` and printer `v0.2.0`. When `npm i printer` I got:
```
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2736, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 412, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1283, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1298, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1283, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1302, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, phase, variables, build_file)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 900, in ExpandVariables
    cwd=build_file_dir)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

How can I successfully build this package under arm arch?
I'm using Arch Linux up-to-date on a Pi B+ (ARMv6)

**Comment by tojocky** [comment]
It is most likely the issue with node or node-gyp issue. What file is missing?

**Comment by arathael** [comment]
That is a great question, it doesn't explicitely logs the missing file. There must be a flag to do so or a system journal that pops the missing filename. I will look into that, but so far I still don't know.

**Comment by arathael** [comment]
Trying to isolate the issue, I found that building on Raspbian do works (using `nvm` anyway). So I'm going to put this on the "archlinux" shitbag.
