### ISSUE TITLE
CentOS7 install ndoe-printer fail

### ISSUE THREAD

**Issue by Dn9x** [tojocky/node-printer#98]
i use npm install printer fail. log:

```
-
> printer@0.2.1 install /var/www/kmt-qualitytracking/node_modules/printer
> node-gyp rebuild

/bin/sh: cups-config: 未找到命令
gyp: Call to 'cups-config --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/kmt-qualitytracking/node_modules/printer
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "install" "printer"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! printer@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the printer@0.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the printer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls printer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/kmt-qualitytracking/npm-debug.log
```

i am use mac book pro, i can install printer, i run `cups-config --libs` this command, result is :+1: 
`-lcups -weak_framework Kerberos -weak_framework GSS -lz -lpthread -lresolv -framework SystemConfiguration -framework CoreFoundation -framework Security -liconv -lz`.
in centos7 not have `cups-config --libs`. 
in centos7 already instal cups, but dont have `cups-config` command. i dont know how to fix, can you help me ??

**Comment by dorshay6** [comment]
+1

**Comment by tojocky** [comment]
IT should Be http://www.unix.com/man-page/centos/1/cups-config/

**Comment by dorshay6** [comment]
I have the problem on ubuntu

**Comment by dmgawel** [comment]
Same on Ubuntu 14.04, CUPS 1.7.2

**Comment by dmgawel** [comment]
Solved: libcups2-dev is required.
